modLoader="javafml"
loaderVersion="[11,)"
license="MIT"
issueTrackerURL="https://github.com/brainage04/SpawnCommands/issues"

[[mods]]
modId="spawncommands"
version="${version}"
displayName="SpawnCommands"
iconFile="assets/spawncommands/icon.png"
authors="brainage04"
description='''Adds world, personal, and shared player spawn commands.'''
displayURL="https://github.com/brainage04/SpawnCommands"

[[dependencies.spawncommands]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},26.3)"
ordering="NONE"
side="BOTH"

[[dependencies.spawncommands]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version},26.3)"
ordering="NONE"
side="BOTH"
